name: Publish

on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Rollback Release
        if: failure()
        uses: author/action-rollback@stable
        with:
          # Using a tag name
          tag: 'G1_DONE'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}