# Reference: https://github.com/marketplace/actions/automatic-revert

name: Rollback

on:
  pull_request:
    branches: master
  issue_comment:
    types: [created]

jobs:
  revert-commit:
    runs-on: ubuntu-latest

    if: contains(github.event.comment.body, '/revert')

    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2

      - name: Automatic Revert
        uses: srt32/revert@v0.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}